### PR TITLE
fix: ordered searches

### PR DESCRIPTION
**Pull request by dopry**

### CODE REVIEW

**Comment by dopry** [comment]
@zerolab this should finally get the ordering working properly with search.  The testing would be better if we could use postgres, since sqlite doesn't support search scoring.

**Comment by zerolab** [comment]
For postgres tests: would need something like https://github.com/torchbox/wagtailmedia/blob/main/.github/workflows/test.yml#L28-L35 and probably just the latest wagtail version for testing (because why not?)
and use dj-database-url in settings or something like https://github.com/torchbox/wagtailmedia/blob/main/tests/settings.py#L11-L22, defaulting to sqlite

**Comment by dopry** [comment]
I can totally setup the workflows I have it on plenty of projects. I'm more concerned about how to test with both sqllite and postgres since they'll both return different results or natural search.

**Comment by dopry** [comment]
This currently passes with sqllite and is working in our development and uat environments. (The previous code I primarily unit tested and assumed it was good... bad assumption)

**Comment by zerolab** [comment]
ah, I see now. I wonder if we add another test which we skip unless the db is postgres. One for a follow up PR

**Review by zerolab — APPROVED** [review]

**Comment by dopry** [comment]
👍 Thanks for getting this in! I can get off my fork and back up upstream.  🎉

**Comment by zerolab** [comment]
https://github.com/torchbox/wagtail-grapple/releases/tag/v0.19.2 - should be on PyPI on 5 or so mins

**Pull request merged**
