### PR TITLE
chore: upgrade graphiql to 2.0.13, react to 18.2.0

### PR DESCRIPTION
**Pull request by dopry**

### CODE REVIEW

**Comment by zerolab** [comment]
@dopry I believe there's also a React dependency there, and the underlying template (https://github.com/torchbox/wagtail-grapple/blob/main/grapple/templates/grapple/graphiql.html) changes too
https://github.com/graphql/graphiql/blob/main/packages/graphiql/CHANGELOG.md

so

**Comment by dopry** [comment]
There is nothing in the changelog about dropping React 16 support. I have been using this every day for about 3 weeks.
I'm not using subscriptions though, so I can't speak to those.

**Comment by zerolab** [comment]
I will try to find some time over the weekend to test this locally

Thanks for double checking the react deps

**Comment by dopry** [comment]
I can update react as well, if you'd like. 16.x is already EOL. 18.2.0 seems to work fine. I'm happy to make the change if you'd like that as well...

**Comment by dopry** [comment]
@zerolab let me know if there are any other changes you want. I went ahead and updated react to 18.2.0 as well.

**Comment by zerolab** [comment]
Aiming to look at this tonight (as I was not well over the weekend)

**Comment by zerolab** [comment]
released v0.18.1, should be on PyPi soon

**Comment by dopry** [comment]
woot!

**Comment by zerolab** [comment]
Thank you for this @dopry
Every little bit helps!

**Pull request merged**
