### PR TITLE
Exposes urlPath argument for page queries within a site query.

### PR DESCRIPTION
**Pull request by paul-apacio**

### CODE REVIEW

**Comment by zerolab** [comment]
Hey @paul-apacio could you add a test please?

**Comment by paul-apacio** [comment]
Ah yes. Sure will do.

**Comment by dopry** [comment]
@paul-apacio do you have time or interest to wrap up this PR?

**Comment by dopry** [comment]
@zerolab how do you want to proceed on this PR? @paul-apacio doesn't seem to be responding, do you feel it is important enough that one of us should wrap it up?

**Comment by zerolab** [comment]
I have not had the need for this personally, but it sounds to me this relates to #306 from a quick glance?

**Comment by dopry** [comment]
It seems trivials and also looks like @engAmireng is also working on something similar. I'm going to close this in favor of active ongoing work and issues else where.

**Pull request closed without merging**
