### PR TITLE
Fix problem in registering and querying custom rendition model

### PR DESCRIPTION
**Pull request by engAmirEng**
This feature implemented for (#16) and wasn't working up to now and the issue (#311)
is refrencing this.
As I was exploring this I found some serious bugs and architectural Issues that I'm going to open later.

### CODE REVIEW

**Comment by engAmirEng** [comment]
@zerolab Do you know about this CI failure?

**Comment by zerolab** [comment]
It is Wagtail 4.2 issue. Will sort it out.
In the meantime, any chance you can add a test?

**Comment by dopry** [comment]
@engAmirEng It's important we try to get tests in to avoid regressions. Tests might have prevented this bug in the first place.  Admittedly the test in grapple are not well organized at the moment and are fully dependent on the example app. 

I think there are two things we would want to test.

1. Is there an image rendition type in the schema?

   we should add a test_graphql_schema.py  in example/home/test. From on of my projects I have https://gist.github.com/dopry/37c6bee35eec0d28483ad8a29fa793bf that could serve as a template. 
  
2. Can we still query renditions?

    I think this could be added in https://github.com/torchbox/wagtail-grapple/blob/main/example/home/test/test_blog.py  in test_blog_body_imagechooserblock and  test_blog_body_imagechooserblock_in_streamblock to ensure renditions can be queried in both contexts. 
   

I'm not sure if testing should hold up this particular PR given it doesn't already have test coverage and we're fixing a pretty obvious production bug. It would be great if you could take a stab at the test.  Ultimately whether tests are required is @zerolab's call.

**Comment by engAmirEng** [comment]
I'll take care of that, might take some time

**Comment by dopry** [comment]
@engAmirEng can you rebase your branch, I want to see if the pre-commit tests are still failing.

**Comment by engAmirEng** [comment]
> @engAmirEng It's awesome the existing tests are passing. The last thing blocking this getting in is some tests. Do you have time to work on those? I'd love to get this in along with the hostname/multitenancy work you've been doing.

Honestly writing tests are not my strong suit, I tried to write the test you are asking for but I couldn't figure it out

**Comment by dopry** [comment]
I understand it can be difficult to get used to writing tests... Normally the approach I take is to write  a test with the old code to demonstrate that the thing I am fixing is broken.  Then I develop my code against that test. Would you be open to some guidance on the test development, and/or another contributor submitting tests to your branch?

**Comment by engAmirEng** [comment]
> I understand it can be difficult to get used to writing tests... Normally the approach I take is to write a test with the old code to demonstrate that the thing I am fixing is broken. Then I develop my code against that test. Would you be open to some guidance on the test development, and/or another contributor submitting tests to your branch?

I will give it another shot today and give you the feedback

**Comment by zerolab** [comment]
I've folded this into #337
Thank you @engAmirEng

**Comment by engAmirEng** [comment]
> I've folded this into #337
> Thank you @engAmirEng 

Happy to see the repo is going forward

**Pull request closed without merging**
