### PR TITLE
Feature/circle ci

### PR DESCRIPTION
**Pull request by jafacakes2011**

### CODE REVIEW

**Comment by jafacakes2011** [comment]
The issue is with the database. We need to either remove the DB and build a new one for the test. Or work out how to make the DB work with the test script

**Comment by jafacakes2011** [comment]
We are still getting the DB issue, but LFS is now available in the test scripts so we should be closer.

**Comment by jafacakes2011** [comment]
FIXED!

**Comment by zerolab** [comment]
Nice one! I suggest merging this with squashed commits so the history is clean and doesn't contain all the intermediary attempts

**Pull request merged**
